### ISSUE TITLE
Widget fingerprint

### ISSUE THREAD

**Issue by 00Kush00** [MrAlpha786/termux-fingerprint-lock#3]
Very cool script. It's possible to protect termux widgets with fingerprint too? I have widgets to ssh in my machines who don't have passwords but keyfile. Anyone with phone access can ssh in my machines..

**Comment by MrAlpha786** [comment]
Hi,
As you described, you use termux to ssh into your machine.
I will suggest you to don't use this lock as it can be easily bypassed using termux failsafe and then can be easily removed from there.

It's just a (as you said) cool thing. But not safe. Maybe, I should add a disclaimer.

You should use some other methods to lock termux (like applocks).

And if you still want to use this. There is a workaround to lock termux widget shortcuts. Just add login command in your shortcut script. 
e.g. - login && ssh <your command>
